#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp.Resource", IsApplication=true)]

namespace Xamarin.Droid.CrossWalkLite.MultiAbi.DemoApp
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f0a0000
			public const int xwalk_resources_list = 2131361792;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int buttonColor = 2130771970;
			
			// aapt resource value: 0x7f010000
			public const int select_dialog_multichoice = 2130771968;
			
			// aapt resource value: 0x7f010001
			public const int select_dialog_singlechoice = 2130771969;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f060001
			public const int color_picker_background_color = 2131099649;
			
			// aapt resource value: 0x7f060000
			public const int color_picker_border_color = 2131099648;
			
			// aapt resource value: 0x7f060003
			public const int dropdown_dark_divider_color = 2131099651;
			
			// aapt resource value: 0x7f060002
			public const int dropdown_divider_color = 2131099650;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f070002
			public const int color_button_height = 2131165186;
			
			// aapt resource value: 0x7f070001
			public const int color_picker_gradient_margin = 2131165185;
			
			// aapt resource value: 0x7f070005
			public const int config_min_scaling_span = 2131165189;
			
			// aapt resource value: 0x7f070006
			public const int config_min_scaling_touch_major = 2131165190;
			
			// aapt resource value: 0x7f070004
			public const int dropdown_item_divider_height = 2131165188;
			
			// aapt resource value: 0x7f070003
			public const int dropdown_item_height = 2131165187;
			
			// aapt resource value: 0x7f070007
			public const int keyboard_accessory_chip_height = 2131165191;
			
			// aapt resource value: 0x7f070008
			public const int keyboard_accessory_fading_edge_length = 2131165192;
			
			// aapt resource value: 0x7f070009
			public const int keyboard_accessory_half_padding = 2131165193;
			
			// aapt resource value: 0x7f07000a
			public const int keyboard_accessory_height = 2131165194;
			
			// aapt resource value: 0x7f07000b
			public const int keyboard_accessory_padding = 2131165195;
			
			// aapt resource value: 0x7f07000c
			public const int keyboard_accessory_text_size = 2131165196;
			
			// aapt resource value: 0x7f070000
			public const int link_preview_overlay_radius = 2131165184;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int autofill_chip_inset = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int bubble = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int bubble_arrow_up = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int button_borderless_compat = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int button_compat = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int button_compat_shape = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int color_button_background = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int color_picker_advanced_select_handle = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int color_picker_border = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int dropdown_popup_background = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int dropdown_popup_background_down = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int dropdown_popup_background_up = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int ic_menu_share_holo_light = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int ic_search = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int ic_warning = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int Icon = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int ondemand_overlay = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int verify_checkmark = 2130837521;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090017
			public const int MyButton = 2131296279;
			
			// aapt resource value: 0x7f09001e
			public const int ampm = 2131296286;
			
			// aapt resource value: 0x7f090025
			public const int arrow_image = 2131296293;
			
			// aapt resource value: 0x7f090001
			public const int autofill_keyboard_accessory_item_label = 2131296257;
			
			// aapt resource value: 0x7f090002
			public const int autofill_keyboard_accessory_item_sublabel = 2131296258;
			
			// aapt resource value: 0x7f090028
			public const int color_button_swatch = 2131296296;
			
			// aapt resource value: 0x7f090007
			public const int color_picker_advanced = 2131296263;
			
			// aapt resource value: 0x7f090008
			public const int color_picker_simple = 2131296264;
			
			// aapt resource value: 0x7f09000e
			public const int date_picker = 2131296270;
			
			// aapt resource value: 0x7f090010
			public const int date_time_suggestion = 2131296272;
			
			// aapt resource value: 0x7f090012
			public const int date_time_suggestion_label = 2131296274;
			
			// aapt resource value: 0x7f090011
			public const int date_time_suggestion_value = 2131296273;
			
			// aapt resource value: 0x7f090016
			public const int dropdown_icon = 2131296278;
			
			// aapt resource value: 0x7f090014
			public const int dropdown_label = 2131296276;
			
			// aapt resource value: 0x7f090013
			public const int dropdown_label_wrapper = 2131296275;
			
			// aapt resource value: 0x7f090000
			public const int dropdown_popup_window = 2131296256;
			
			// aapt resource value: 0x7f090015
			public const int dropdown_sublabel = 2131296277;
			
			// aapt resource value: 0x7f090005
			public const int gradient = 2131296261;
			
			// aapt resource value: 0x7f090004
			public const int gradient_border = 2131296260;
			
			// aapt resource value: 0x7f090018
			public const int hour = 2131296280;
			
			// aapt resource value: 0x7f090023
			public const int icon_view = 2131296291;
			
			// aapt resource value: 0x7f090026
			public const int main_text = 2131296294;
			
			// aapt resource value: 0x7f09001d
			public const int milli = 2131296285;
			
			// aapt resource value: 0x7f090019
			public const int minute = 2131296281;
			
			// aapt resource value: 0x7f09000a
			public const int more_colors_button = 2131296266;
			
			// aapt resource value: 0x7f090009
			public const int more_colors_button_border = 2131296265;
			
			// aapt resource value: 0x7f09001f
			public const int pickers = 2131296287;
			
			// aapt resource value: 0x7f090020
			public const int position_in_year = 2131296288;
			
			// aapt resource value: 0x7f09001b
			public const int second = 2131296283;
			
			// aapt resource value: 0x7f09001a
			public const int second_colon = 2131296282;
			
			// aapt resource value: 0x7f09001c
			public const int second_dot = 2131296284;
			
			// aapt resource value: 0x7f090006
			public const int seek_bar = 2131296262;
			
			// aapt resource value: 0x7f09002b
			public const int select_action_menu_copy = 2131296299;
			
			// aapt resource value: 0x7f09002a
			public const int select_action_menu_cut = 2131296298;
			
			// aapt resource value: 0x7f09002c
			public const int select_action_menu_paste = 2131296300;
			
			// aapt resource value: 0x7f090029
			public const int select_action_menu_select_all = 2131296297;
			
			// aapt resource value: 0x7f09002d
			public const int select_action_menu_share = 2131296301;
			
			// aapt resource value: 0x7f09002e
			public const int select_action_menu_web_search = 2131296302;
			
			// aapt resource value: 0x7f09000d
			public const int selected_color_view = 2131296269;
			
			// aapt resource value: 0x7f09000c
			public const int selected_color_view_border = 2131296268;
			
			// aapt resource value: 0x7f090027
			public const int sub_text = 2131296295;
			
			// aapt resource value: 0x7f090003
			public const int text = 2131296259;
			
			// aapt resource value: 0x7f090024
			public const int text_wrapper = 2131296292;
			
			// aapt resource value: 0x7f09000f
			public const int time_picker = 2131296271;
			
			// aapt resource value: 0x7f09000b
			public const int title = 2131296267;
			
			// aapt resource value: 0x7f090022
			public const int top_view = 2131296290;
			
			// aapt resource value: 0x7f090021
			public const int year = 2131296289;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int autofill_keyboard_accessory_icon = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int autofill_keyboard_accessory_item = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int color_picker_advanced_component = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int color_picker_dialog_content = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int color_picker_dialog_title = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int date_time_picker_dialog = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int date_time_suggestion = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int dropdown_item = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int Main = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int multi_field_time_picker_dialog = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int two_field_date_picker = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int validation_message_bubble = 2130903051;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f0b0000
			public const int select_action_menu = 2131427328;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class Raw
		{
			
			// aapt resource value: 0x7f040000
			public const int xwalk = 2130968576;
			
			static Raw()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Raw()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f05005d
			public const int ApplicationName = 2131034205;
			
			// aapt resource value: 0x7f05005c
			public const int Hello = 2131034204;
			
			// aapt resource value: 0x7f05001d
			public const int accessibility_date_picker_month = 2131034141;
			
			// aapt resource value: 0x7f050021
			public const int accessibility_date_picker_week = 2131034145;
			
			// aapt resource value: 0x7f05001e
			public const int accessibility_date_picker_year = 2131034142;
			
			// aapt resource value: 0x7f05002f
			public const int accessibility_datetime_picker_date = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int accessibility_datetime_picker_time = 2131034160;
			
			// aapt resource value: 0x7f05002a
			public const int accessibility_time_picker_ampm = 2131034154;
			
			// aapt resource value: 0x7f050026
			public const int accessibility_time_picker_hour = 2131034150;
			
			// aapt resource value: 0x7f050029
			public const int accessibility_time_picker_milli = 2131034153;
			
			// aapt resource value: 0x7f050027
			public const int accessibility_time_picker_minute = 2131034151;
			
			// aapt resource value: 0x7f050028
			public const int accessibility_time_picker_second = 2131034152;
			
			// aapt resource value: 0x7f050000
			public const int actionbar_share = 2131034112;
			
			// aapt resource value: 0x7f050001
			public const int actionbar_web_search = 2131034113;
			
			// aapt resource value: 0x7f050034
			public const int autofill_popup_content_description = 2131034164;
			
			// aapt resource value: 0x7f05001a
			public const int color_picker_button_black = 2131034138;
			
			// aapt resource value: 0x7f050016
			public const int color_picker_button_blue = 2131034134;
			
			// aapt resource value: 0x7f050012
			public const int color_picker_button_cancel = 2131034130;
			
			// aapt resource value: 0x7f050015
			public const int color_picker_button_cyan = 2131034133;
			
			// aapt resource value: 0x7f050017
			public const int color_picker_button_green = 2131034135;
			
			// aapt resource value: 0x7f050018
			public const int color_picker_button_magenta = 2131034136;
			
			// aapt resource value: 0x7f05000d
			public const int color_picker_button_more = 2131034125;
			
			// aapt resource value: 0x7f050014
			public const int color_picker_button_red = 2131034132;
			
			// aapt resource value: 0x7f050011
			public const int color_picker_button_set = 2131034129;
			
			// aapt resource value: 0x7f05001b
			public const int color_picker_button_white = 2131034139;
			
			// aapt resource value: 0x7f050019
			public const int color_picker_button_yellow = 2131034137;
			
			// aapt resource value: 0x7f050013
			public const int color_picker_dialog_title = 2131034131;
			
			// aapt resource value: 0x7f05000e
			public const int color_picker_hue = 2131034126;
			
			// aapt resource value: 0x7f05000f
			public const int color_picker_saturation = 2131034127;
			
			// aapt resource value: 0x7f050010
			public const int color_picker_value = 2131034128;
			
			// aapt resource value: 0x7f05001c
			public const int copy_to_clipboard_failure_message = 2131034140;
			
			// aapt resource value: 0x7f050043
			public const int crosswalk_install_title = 2131034179;
			
			// aapt resource value: 0x7f050033
			public const int date_picker_dialog_clear = 2131034163;
			
			// aapt resource value: 0x7f050031
			public const int date_picker_dialog_other_button_label = 2131034161;
			
			// aapt resource value: 0x7f05001f
			public const int date_picker_dialog_set = 2131034143;
			
			// aapt resource value: 0x7f050032
			public const int date_picker_dialog_title = 2131034162;
			
			// aapt resource value: 0x7f05002e
			public const int date_time_picker_dialog_title = 2131034158;
			
			// aapt resource value: 0x7f050044
			public const int decompression_progress_message = 2131034180;
			
			// aapt resource value: 0x7f05003b
			public const int download_already_exists_toast = 2131034171;
			
			// aapt resource value: 0x7f050047
			public const int download_failed_device_not_found = 2131034183;
			
			// aapt resource value: 0x7f050048
			public const int download_failed_insufficient_space = 2131034184;
			
			// aapt resource value: 0x7f050046
			public const int download_failed_message = 2131034182;
			
			// aapt resource value: 0x7f050049
			public const int download_failed_time_out = 2131034185;
			
			// aapt resource value: 0x7f05003c
			public const int download_failed_toast = 2131034172;
			
			// aapt resource value: 0x7f05003d
			public const int download_finished_toast = 2131034173;
			
			// aapt resource value: 0x7f05003a
			public const int download_no_permission_toast = 2131034170;
			
			// aapt resource value: 0x7f050045
			public const int download_progress_message = 2131034181;
			
			// aapt resource value: 0x7f050039
			public const int download_start_toast = 2131034169;
			
			// aapt resource value: 0x7f050042
			public const int http_auth_log_in = 2131034178;
			
			// aapt resource value: 0x7f050041
			public const int http_auth_password = 2131034177;
			
			// aapt resource value: 0x7f05003f
			public const int http_auth_title = 2131034175;
			
			// aapt resource value: 0x7f050040
			public const int http_auth_user_name = 2131034176;
			
			// aapt resource value: 0x7f050036
			public const int js_alert_title = 2131034166;
			
			// aapt resource value: 0x7f050037
			public const int js_confirm_title = 2131034167;
			
			// aapt resource value: 0x7f050038
			public const int js_prompt_title = 2131034168;
			
			// aapt resource value: 0x7f05000b
			public const int low_memory_error = 2131034123;
			
			// aapt resource value: 0x7f05004a
			public const int market_open_failed_message = 2131034186;
			
			// aapt resource value: 0x7f050005
			public const int media_player_error_button = 2131034117;
			
			// aapt resource value: 0x7f050003
			public const int media_player_error_text_invalid_progressive_playback = 2131034115;
			
			// aapt resource value: 0x7f050004
			public const int media_player_error_text_unknown = 2131034116;
			
			// aapt resource value: 0x7f050002
			public const int media_player_error_title = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int media_player_loading_video = 2131034118;
			
			// aapt resource value: 0x7f050020
			public const int month_picker_dialog_title = 2131034144;
			
			// aapt resource value: 0x7f05000c
			public const int opening_file_error = 2131034124;
			
			// aapt resource value: 0x7f050035
			public const int password_generation_popup_content_description = 2131034165;
			
			// aapt resource value: 0x7f05000a
			public const int profiler_error_toast = 2131034122;
			
			// aapt resource value: 0x7f050009
			public const int profiler_no_storage_toast = 2131034121;
			
			// aapt resource value: 0x7f050007
			public const int profiler_started_toast = 2131034119;
			
			// aapt resource value: 0x7f050008
			public const int profiler_stopped_toast = 2131034120;
			
			// aapt resource value: 0x7f05003e
			public const int ssl_alert_title = 2131034174;
			
			// aapt resource value: 0x7f050054
			public const int startup_architecture_mismatch_message = 2131034196;
			
			// aapt resource value: 0x7f050053
			public const int startup_architecture_mismatch_title = 2131034195;
			
			// aapt resource value: 0x7f050052
			public const int startup_incomplete_library_message = 2131034194;
			
			// aapt resource value: 0x7f050051
			public const int startup_incomplete_library_title = 2131034193;
			
			// aapt resource value: 0x7f050050
			public const int startup_newer_version_message = 2131034192;
			
			// aapt resource value: 0x7f05004f
			public const int startup_newer_version_title = 2131034191;
			
			// aapt resource value: 0x7f05004c
			public const int startup_not_found_message = 2131034188;
			
			// aapt resource value: 0x7f05004b
			public const int startup_not_found_title = 2131034187;
			
			// aapt resource value: 0x7f05004e
			public const int startup_older_version_message = 2131034190;
			
			// aapt resource value: 0x7f05004d
			public const int startup_older_version_title = 2131034189;
			
			// aapt resource value: 0x7f050056
			public const int startup_signature_check_error_message = 2131034198;
			
			// aapt resource value: 0x7f050055
			public const int startup_signature_check_error_title = 2131034197;
			
			// aapt resource value: 0x7f050023
			public const int time_picker_dialog_am = 2131034147;
			
			// aapt resource value: 0x7f05002b
			public const int time_picker_dialog_hour_minute_separator = 2131034155;
			
			// aapt resource value: 0x7f05002c
			public const int time_picker_dialog_minute_second_separator = 2131034156;
			
			// aapt resource value: 0x7f050024
			public const int time_picker_dialog_pm = 2131034148;
			
			// aapt resource value: 0x7f05002d
			public const int time_picker_dialog_second_subsecond_separator = 2131034157;
			
			// aapt resource value: 0x7f050025
			public const int time_picker_dialog_title = 2131034149;
			
			// aapt resource value: 0x7f050022
			public const int week_picker_dialog_title = 2131034146;
			
			// aapt resource value: 0x7f050058
			public const int xwalk_cancel = 2131034200;
			
			// aapt resource value: 0x7f05005a
			public const int xwalk_close = 2131034202;
			
			// aapt resource value: 0x7f050059
			public const int xwalk_continue = 2131034201;
			
			// aapt resource value: 0x7f050057
			public const int xwalk_get_crosswalk = 2131034199;
			
			// aapt resource value: 0x7f05005b
			public const int xwalk_retry = 2131034203;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080007
			public const int ButtonCompat = 2131230727;
			
			// aapt resource value: 0x7f080006
			public const int ButtonCompatBase = 2131230726;
			
			// aapt resource value: 0x7f080008
			public const int ButtonCompatBorderless = 2131230728;
			
			// aapt resource value: 0x7f080005
			public const int ButtonCompatBorderlessOverlay = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int ButtonCompatOverlay = 2131230724;
			
			// aapt resource value: 0x7f080003
			public const int DropdownPopupWindow = 2131230723;
			
			// aapt resource value: 0x7f080001
			public const int SelectActionMenuShare = 2131230721;
			
			// aapt resource value: 0x7f080002
			public const int SelectActionMenuWebSearch = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int SelectPopupDialog = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] ButtonCompat = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int ButtonCompat_buttonColor = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
